In [41]:
import boto3
import pandas as pd

s3=boto3.client('s3')

In [42]:
s3 = boto3.resource(
    service_name='s3',
    region_name='us-west-2',
    aws_access_key_id='',
    aws_secret_access_key=''
)

In [43]:
buck=s3.Bucket('lms29')

#for obj in buck.objects.all():
    #print(obj.key)

### Reading CSV Files from the bucket

In [44]:
obj1=buck.Object('csv/df1.csv').get()
df1=pd.read_csv(obj1['Body'])

In [45]:
df1

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
954,7.6,0.43,0.40,2.7,0.082,6.0,11.0,0.99538,3.44,0.54,12.2,6
955,8.5,0.21,0.52,1.9,0.090,9.0,23.0,0.99648,3.36,0.67,10.4,5
956,9.0,0.36,0.52,2.1,0.111,5.0,10.0,0.99568,3.31,0.62,11.3,6
957,9.5,0.37,0.52,2.0,0.088,12.0,51.0,0.99613,3.29,0.58,11.1,6
958,6.4,0.57,0.12,2.3,0.120,25.0,36.0,0.99519,3.47,0.71,11.3,7

In [46]:
obj2=buck.Object('csv/df2.csv').get()
df2=pd.read_csv(obj2['Body'])

In [47]:
df2

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,8.0,0.590,0.05,2.0,0.089,12.0,32.0,0.99735,3.36,0.61,10.0,5
1,8.5,0.470,0.27,1.9,0.058,18.0,38.0,0.99518,3.16,0.85,11.1,6
2,7.1,0.560,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3,5
3,6.6,0.570,0.02,2.1,0.115,6.0,16.0,0.99654,3.38,0.69,9.5,5
4,8.8,0.270,0.39,2.0,0.100,20.0,27.0,0.99546,3.15,0.69,11.2,6
...,...,...,...,...,...,...,...,...,...,...,...,...
315,7.8,0.580,0.13,2.1,0.102,17.0,36.0,0.99440,3.24,0.53,11.2,6
316,8.0,0.715,0.22,2.3,0.075,13.0,81.0,0.99688,3.24,0.54,9.5,6
317,8.5,0.400,0.40,6.3,0.050,3.0,10.0,0.99566,3.28,0.56,12.0,4
318,7.0,0.690,0.00,1.9,0.114,3.0,10.0,0.99636,3.35,0.60,9.7,6
319,8.0,0.715,0.22,2.3,0.075,13.0,81.0,0.99688,3.24,0.54,9.5,6

In [48]:
obj3=buck.Object('csv/df3.csv').get()
df3=pd.read_csv(obj3['Body'])

In [49]:
df3

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,9.8,0.300,0.39,1.7,0.062,3.0,9.0,0.99480,3.14,0.57,11.5,7
1,7.1,0.460,0.20,1.9,0.077,28.0,54.0,0.99560,3.37,0.64,10.4,6
2,7.1,0.460,0.20,1.9,0.077,28.0,54.0,0.99560,3.37,0.64,10.4,6
3,7.9,0.765,0.00,2.0,0.084,9.0,22.0,0.99619,3.33,0.68,10.9,6
4,8.7,0.630,0.28,2.7,0.096,17.0,69.0,0.99734,3.26,0.63,10.2,6
...,...,...,...,...,...,...,...,...,...,...,...,...
315,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
316,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
317,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
318,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
319,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

### Combining Dataset

In [50]:
df=pd.concat([df1,df2,df3])

In [51]:
df=df.reset_index()

In [52]:
df

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,315,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,316,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,317,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,318,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,319,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

### Specifying Train and Test Dataset

In [53]:
train=df1

In [54]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
954,7.6,0.43,0.40,2.7,0.082,6.0,11.0,0.99538,3.44,0.54,12.2,6
955,8.5,0.21,0.52,1.9,0.090,9.0,23.0,0.99648,3.36,0.67,10.4,5
956,9.0,0.36,0.52,2.1,0.111,5.0,10.0,0.99568,3.31,0.62,11.3,6
957,9.5,0.37,0.52,2.0,0.088,12.0,51.0,0.99613,3.29,0.58,11.1,6
958,6.4,0.57,0.12,2.3,0.120,25.0,36.0,0.99519,3.47,0.71,11.3,7

In [55]:
test=pd.concat([df2,df3])

In [56]:
test=test.reset_index()

In [57]:
testf=test.iloc[:,1:13]

In [58]:
testf

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,8.0,0.590,0.05,2.0,0.089,12.0,32.0,0.99735,3.36,0.61,10.0,5
1,8.5,0.470,0.27,1.9,0.058,18.0,38.0,0.99518,3.16,0.85,11.1,6
2,7.1,0.560,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3,5
3,6.6,0.570,0.02,2.1,0.115,6.0,16.0,0.99654,3.38,0.69,9.5,5
4,8.8,0.270,0.39,2.0,0.100,20.0,27.0,0.99546,3.15,0.69,11.2,6
...,...,...,...,...,...,...,...,...,...,...,...,...
635,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
636,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
637,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
638,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
639,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

### Saving Train and Test Dataset as CSV file

In [59]:
train.to_csv('automl-train.csv', index=False, header=True, sep=',') # Need to keep column names
testf.to_csv('automl-test.csv', index=False, header=True, sep=',')

In [60]:
import sagemaker

sess=sagemaker.Session()
lm=sess.upload_data(path="automl-train.csv")
print(lm)

s3://sagemaker-us-west-2-313830654669/data/automl-train.csv

### After Autopilot Experiment, Best model is deployed as endpoint

In [61]:
ep_name = 'bestmodel29'

In [62]:
import boto3,sys

sm_rt = boto3.Session().client('runtime.sagemaker')

### Checking the results against the labels of test dataset

In [63]:
res=[]
with open('automl-test.csv') as f:
    lines = f.readlines()
    for l in lines[1:]:   
        l = l.split(',')  
        label = l[-1]     
        l = l[:-1]        
        l = ','.join(l)   
                
        response = sm_rt.invoke_endpoint(EndpointName=ep_name, ContentType='text/csv', Accept='text/csv', Body=l)

        response = response['Body'].read().decode("utf-8")
        res.append(response[0])
        #print ("label %s response %s" %(label,response))

In [64]:
testf['Predicted']=res

In [65]:
testf.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Predicted
0,8.0,0.59,0.05,2.0,0.089,12.0,32.0,0.99735,3.36,0.61,10.0,5,6
1,8.5,0.47,0.27,1.9,0.058,18.0,38.0,0.99518,3.16,0.85,11.1,6,6
2,7.1,0.56,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3,5,5
3,6.6,0.57,0.02,2.1,0.115,6.0,16.0,0.99654,3.38,0.69,9.5,5,5
4,8.8,0.27,0.39,2.0,0.100,20.0,27.0,0.99546,3.15,0.69,11.2,6,6